# Generated by Django 6.0.3 on 2026-03-30 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_productimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("address_line", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("PROCESSING", "Processing"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("shipping_address", models.TextField()),
                ("shipping_city", models.CharField(max_length=100)),
                ("shipping_state", models.CharField(max_length=100)),
                ("shipping_country", models.CharField(default="India", max_length=100)),
                ("shipping_zip_code", models.CharField(max_length=20)),
                ("shipping_phone", models.CharField(max_length=15)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "shiprocket_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("awb_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "courier_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ecommerce.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                through="ecommerce.OrderItem", to="ecommerce.product"
            ),
        ),
    ]
