trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '20.x'

steps:

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: 'Install Node.js'

# Install Dependencies
- script: |
    npm cache clean --force
    rm -rf node_modules package-lock.json
    npm install
  displayName: 'Install Dependencies'

# Build Frontend
- script: |
    npm run build
  displayName: 'Build Frontend'

# Archive Application
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
