trigger:
- ver-1.1.1

pool:
  name: bbo-dev

steps:

- task: UseNode@1
  inputs:
    version: '18.x'

- script: npm install
  displayName: Install Dependencies

- script: npm run build
  displayName: Build Frontend

- script: |
    sudo rm -rf /usr/share/nginx/html/*
    sudo cp -r dist/* /usr/share/nginx/html/
  displayName: Deploy to Nginx

- script: sudo systemctl restart nginx
  displayName: Restart Nginx

